{
  "openapi": "3.0.1",
  "info": {
    "title": "个人项目",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "宠物"
    }
  ],
  "paths": {
    "/pet/{petId}": {
      "post": {
        "summary": "查询宠物详情（单层无object嵌套）",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "productName",
            "in": "cookie",
            "description": "",
            "required": true,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "cookie",
            "description": "",
            "required": true,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "cookie",
            "description": "",
            "required": true,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "cookie",
            "description": "",
            "required": true,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "cookie",
            "description": "",
            "required": true,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "cookie",
            "description": "",
            "required": true,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "cookie",
            "description": "ID 编号",
            "example": "66",
            "schema": {
              "type": "string",
              "default": "66"
            }
          },
          {
            "name": "petId",
            "in": "path",
            "description": "宠物 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productName",
            "in": "query",
            "description": "",
            "required": true,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "query",
            "description": "",
            "required": true,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "query",
            "description": "",
            "required": true,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "query",
            "description": "",
            "required": true,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "query",
            "description": "",
            "required": true,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "query",
            "description": "",
            "required": true,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "category",
            "in": "query",
            "description": "分组",
            "required": false,
            "example": "211212",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "query",
            "description": "ID 编号",
            "example": "112121",
            "schema": {
              "type": "string",
              "default": "112121"
            }
          },
          {
            "name": "productName",
            "in": "header",
            "description": "",
            "required": true,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "header",
            "description": "",
            "required": true,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "header",
            "description": "",
            "required": true,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "header",
            "description": "",
            "required": true,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "header",
            "description": "",
            "required": true,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "header",
            "description": "",
            "required": true,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "5656",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {
                "productName": {
                  "contentType": "application/atom+xml"
                }
              },
              "schema": {
                "type": "object",
                "properties": {
                  "productName": {
                    "example": "T - Shirt",
                    "type": "string"
                  },
                  "productPrice": {
                    "example": 29.99,
                    "type": "number"
                  },
                  "productColor": {
                    "example": "Blue",
                    "type": "string"
                  },
                  "productSize": {
                    "example": "M",
                    "type": "string"
                  },
                  "stockQuantity": {
                    "example": 50,
                    "type": "integer"
                  },
                  "isOnSale": {
                    "example": "true",
                    "type": "boolean"
                  },
                  "id": {
                    "type": "string",
                    "default": "89",
                    "description": "ID 编号",
                    "example": "89"
                  }
                },
                "required": [
                  "productName",
                  "productPrice",
                  "productColor",
                  "productSize",
                  "stockQuantity",
                  "isOnSale"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0,
                      "description": "状态码"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "message"
                  ]
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "message"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "删除宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "productName",
            "in": "cookie",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "cookie",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "cookie",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "cookie",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "cookie",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "cookie",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "cookie",
            "description": "ID 编号",
            "example": "66",
            "schema": {
              "type": "string",
              "default": "66"
            }
          },
          {
            "name": "petId",
            "in": "path",
            "description": "Pet id to delete",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productName",
            "in": "query",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "query",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "query",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "query",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "query",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "query",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "query",
            "description": "ID 编号",
            "example": "112121",
            "schema": {
              "type": "string",
              "default": "112121"
            }
          },
          {
            "name": "api_key",
            "in": "header",
            "description": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productName",
            "in": "header",
            "description": "",
            "required": false,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "header",
            "description": "",
            "required": false,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "header",
            "description": "",
            "required": false,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "header",
            "description": "",
            "required": false,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "header",
            "description": "",
            "required": false,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "5656",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    }
                  },
                  "required": [
                    "code"
                  ]
                },
                "example": {
                  "code": 0
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet": {
      "post": {
        "summary": "新建宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "productName",
            "in": "cookie",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "cookie",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "cookie",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "cookie",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "cookie",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "cookie",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "cookie",
            "description": "ID 编号",
            "example": "66",
            "schema": {
              "type": "string",
              "default": "66"
            }
          },
          {
            "name": "^$*+?.[](){}|\\@",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "中文",
            "in": "query",
            "description": "",
            "required": false,
            "example": 565,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "productName",
            "in": "query",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "query",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "query",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "query",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "query",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "query",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "query",
            "description": "ID 编号",
            "example": "112121",
            "schema": {
              "type": "string",
              "default": "112121"
            }
          },
          {
            "name": "productName",
            "in": "header",
            "description": "",
            "required": false,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "header",
            "description": "",
            "required": false,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "header",
            "description": "",
            "required": false,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "header",
            "description": "",
            "required": false,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "header",
            "description": "",
            "required": false,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "5656",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {
                "productName": {
                  "contentType": "application/atom+xml"
                }
              },
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "宠物名",
                    "example": "Hello Kitty",
                    "type": "string"
                  },
                  "status": {
                    "description": "宠物销售状态",
                    "example": "sold",
                    "type": "string"
                  },
                  "productName": {
                    "example": "T - Shirt",
                    "type": "string"
                  },
                  "productPrice": {
                    "example": 29.99,
                    "type": "number"
                  },
                  "productColor": {
                    "example": "Blue",
                    "type": "string"
                  },
                  "productSize": {
                    "example": "M",
                    "type": "string"
                  },
                  "stockQuantity": {
                    "example": 50,
                    "type": "integer"
                  },
                  "isOnSale": {
                    "example": "true",
                    "type": "boolean"
                  },
                  "id": {
                    "type": "string",
                    "default": "89",
                    "description": "ID 编号",
                    "example": "89"
                  }
                },
                "required": [
                  "name",
                  "status"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "修改宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "productName",
            "in": "cookie",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "cookie",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "cookie",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "cookie",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "cookie",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "cookie",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "cookie",
            "description": "ID 编号",
            "example": "66",
            "schema": {
              "type": "string",
              "default": "66"
            }
          },
          {
            "name": "title",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "type",
            "in": "query",
            "description": "",
            "required": false,
            "example": "object",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productName",
            "in": "query",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "query",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "query",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "query",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "query",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "query",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "query",
            "description": "ID 编号",
            "example": "112121",
            "schema": {
              "type": "string",
              "default": "112121"
            }
          },
          {
            "name": "productName",
            "in": "header",
            "description": "",
            "required": false,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "header",
            "description": "",
            "required": false,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "header",
            "description": "",
            "required": false,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "header",
            "description": "",
            "required": false,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "header",
            "description": "",
            "required": false,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "5656",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "title": "",
                "type": "object",
                "properties": {
                  "id1": {
                    "type": "string",
                    "description": "ID 编号"
                  },
                  "category1": {
                    "type": "string",
                    "description": "分组"
                  },
                  "name1": {
                    "anyOf": [
                      {
                        "type": "object",
                        "properties": {
                          "ss": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "ss"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "dd": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "dd"
                        ]
                      }
                    ],
                    "description": "名称"
                  },
                  "id": {
                    "type": "integer",
                    "format": "int64",
                    "minimum": 1,
                    "description": "分组ID编号"
                  },
                  "name": {
                    "type": "string",
                    "description": "分组名称"
                  }
                },
                "required": [
                  "id1",
                  "category1",
                  "name1"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "405": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet/findByStatus": {
      "get": {
        "summary": "根据状态查找宠物列表",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "productName",
            "in": "cookie",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "cookie",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "cookie",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "cookie",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "cookie",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "cookie",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "cookie",
            "description": "ID 编号",
            "example": "66",
            "schema": {
              "type": "string",
              "default": "66"
            }
          },
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productName",
            "in": "query",
            "description": "",
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "query",
            "description": "",
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "query",
            "description": "",
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "query",
            "description": "",
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "query",
            "description": "",
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "query",
            "description": "",
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "id",
            "in": "query",
            "description": "ID 编号",
            "example": "112121",
            "schema": {
              "type": "string",
              "default": "112121"
            }
          },
          {
            "name": "productName",
            "in": "header",
            "description": "",
            "required": false,
            "example": "T - Shirt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productPrice",
            "in": "header",
            "description": "",
            "required": false,
            "example": 29.99,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "productColor",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Blue",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "productSize",
            "in": "header",
            "description": "",
            "required": false,
            "example": "M",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stockQuantity",
            "in": "header",
            "description": "",
            "required": false,
            "example": 50,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isOnSale",
            "in": "header",
            "description": "",
            "required": false,
            "example": "true",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "5656",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Pet",
                    "description": "宠物信息"
                  }
                },
                "example": {
                  "code": 0,
                  "data": [
                    {
                      "name": "Hello Kity",
                      "photoUrls": [
                        "http://dummyimage.com/400x400"
                      ],
                      "id": 3,
                      "category": {
                        "id": 71,
                        "name": "Cat"
                      },
                      "tags": [
                        {
                          "id": 22,
                          "name": "Cat"
                        }
                      ],
                      "status": "sold"
                    },
                    {
                      "name": "White Dog",
                      "photoUrls": [
                        "http://dummyimage.com/400x400"
                      ],
                      "id": 3,
                      "category": {
                        "id": 71,
                        "name": "Dog"
                      },
                      "tags": [
                        {
                          "id": 22,
                          "name": "Dog"
                        }
                      ],
                      "status": "sold"
                    }
                  ]
                }
              }
            },
            "headers": {}
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "code"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "required": [
          "name",
          "photoUrls",
          "id",
          "category",
          "tags",
          "status"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "宠物ID编号"
          },
          "category": {
            "$ref": "#/components/schemas/Category",
            "description": "分组"
          },
          "name": {
            "type": "string",
            "description": "名称",
            "examples": [
              "doggie"
            ]
          },
          "photoUrls": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "照片URL"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            },
            "description": "标签"
          },
          "status": {
            "type": "string",
            "description": "宠物销售状态",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "分组ID编号"
          },
          "name": {
            "type": "string",
            "description": "分组名称"
          }
        },
        "xml": {
          "name": "Category"
        }
      },
      "Tag": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "标签ID编号"
          },
          "name": {
            "type": "string",
            "description": "标签名称"
          }
        },
        "xml": {
          "name": "Tag"
        }
      }
    },
    "securitySchemes": {
      "123": {
        "type": "apiKey",
        "in": "header"
      },
      "test": {
        "type": "apiKey",
        "in": "header"
      },
      "key": {
        "type": "apiKey",
        "in": "header",
        "name": "121299"
      }
    }
  },
  "servers": [],
  "security": []
}